# Generated by Django 5.2.9 on 2025-12-27 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, help_text='Format: COA-YYYY-NNN ili COB-YYYY-NNN', max_length=20, unique=True, verbose_name='Referentni Broj')),
                ('application_type', models.CharField(choices=[('COA', 'Prijava za Projekat'), ('COB', 'Prijava za Inicijativu')], db_index=True, max_length=3, verbose_name='Tip Prijave')),
                ('status', models.CharField(choices=[('submitted', 'Podneto'), ('under_review', 'U Razmatranju'), ('approved', 'Odobreno'), ('rejected', 'Odbijeno')], db_index=True, default='submitted', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Podneseno')),
            ],
            options={
                'verbose_name': 'Prijava',
                'verbose_name_plural': 'Prijave',
                'ordering': ['-submitted_at', '-created_at'],
                'indexes': [models.Index(fields=['reference_number'], name='submissions_referen_a37c83_idx'), models.Index(fields=['application_type', 'status'], name='submissions_applica_b94d23_idx'), models.Index(fields=['submitted_at'], name='submissions_submitt_0b8c3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('fizicko', 'Fizičko Lice'), ('pravno', 'Pravno Lice')], max_length=10, verbose_name='Tip Podnosioca')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Ime')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Prezime')),
                ('jmbg', models.CharField(blank=True, help_text='13 cifara', max_length=13, null=True, verbose_name='JMBG')),
                ('organization_name', models.CharField(blank=True, max_length=200, verbose_name='Naziv Organizacije')),
                ('maticni_broj', models.CharField(blank=True, help_text='8 cifara', max_length=8, null=True, verbose_name='Matični Broj')),
                ('address', models.CharField(max_length=300, verbose_name='Adresa')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='submissions.application', verbose_name='Prijava')),
            ],
            options={
                'verbose_name': 'Podnosilac',
                'verbose_name_plural': 'Podnosioci',
            },
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('BUDGET', 'Budžet'), ('BIOGRAPHY', 'Biografija'), ('SUPPORT_LETTER', 'Pismo Podrške')], max_length=20, verbose_name='Tip Fajla')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Originalni Naziv')),
                ('stored_filename', models.CharField(max_length=255, verbose_name='Naziv u Skladištu')),
                ('file_size', models.IntegerField(help_text='Bytes', verbose_name='Veličina Fajla')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum Upload-a')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.application', verbose_name='Prijava')),
            ],
            options={
                'verbose_name': 'Metadata Fajla',
                'verbose_name_plural': 'Metadata Fajlova',
            },
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Naslov Projekta')),
                ('short_description', models.TextField(max_length=500, verbose_name='Kratak Opis')),
                ('problem', models.TextField(max_length=2000, verbose_name='Problem')),
                ('main_goal', models.TextField(max_length=1000, verbose_name='Glavni Cilj')),
                ('specific_goals', models.TextField(max_length=1000, verbose_name='Specifični Ciljevi')),
                ('target_groups', models.TextField(max_length=1500, verbose_name='Ciljne Grupe')),
                ('activities', models.TextField(max_length=1500, verbose_name='Aktivnosti')),
                ('results', models.TextField(max_length=1500, verbose_name='Rezultati')),
                ('total_budget', models.IntegerField(help_text='Iznos u RSD', verbose_name='Ukupan Budžet')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_data', to='submissions.application', verbose_name='Prijava')),
            ],
            options={
                'verbose_name': 'Podaci Projekta',
                'verbose_name_plural': 'Podaci Projekata',
            },
        ),
        migrations.CreateModel(
            name='ReferenceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year for this sequence', verbose_name='Godina')),
                ('application_type', models.CharField(choices=[('COA', 'Projekat'), ('COB', 'Inicijativa')], max_length=10, verbose_name='Tip Prijave')),
                ('last_number', models.IntegerField(default=0, help_text='Last assigned sequential number', verbose_name='Poslednji Broj')),
            ],
            options={
                'verbose_name': 'Sekvenca Referentnog Broja',
                'verbose_name_plural': 'Sekvence Referentnih Brojeva',
                'indexes': [models.Index(fields=['year', 'application_type'], name='submissions_year_f20386_idx')],
                'unique_together': {('year', 'application_type')},
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='Original file name as uploaded by user', max_length=255, verbose_name='Originalni Naziv')),
                ('stored_filename', models.CharField(help_text='Unique filename used for storage', max_length=255, unique=True, verbose_name='Naziv u Skladištu')),
                ('file_path', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Putanja Fajla')),
                ('file_size', models.IntegerField(help_text='Size in bytes', verbose_name='Veličina Fajla')),
                ('file_type', models.CharField(help_text='File extension: pdf, doc, docx, xls, xlsx', max_length=10, verbose_name='Tip Fajla')),
                ('mime_type', models.CharField(help_text='Detected MIME type for validation', max_length=100, verbose_name='MIME Tip')),
                ('category', models.CharField(choices=[('BUDGET', 'Budžet'), ('BIOGRAPHY', 'Biografija'), ('SUPPORT_LETTER', 'Pismo Podrške')], help_text='Purpose of uploaded file', max_length=20, verbose_name='Kategorija')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Datum Upload-a')),
                ('uploaded_by_session', models.CharField(db_index=True, help_text='Session key for draft file ownership', max_length=40, verbose_name='Sesija Korisnika')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag', verbose_name='Obrisan')),
                ('application', models.ForeignKey(blank=True, help_text='Linked application (null for draft files)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='submissions.application', verbose_name='Prijava')),
            ],
            options={
                'verbose_name': 'Upload-ovani Fajl',
                'verbose_name_plural': 'Upload-ovani Fajlovi',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['uploaded_by_session'], name='submissions_uploade_b9ba48_idx'), models.Index(fields=['application'], name='submissions_applica_18d36e_idx'), models.Index(fields=['upload_date'], name='submissions_upload__105f27_idx'), models.Index(fields=['is_deleted'], name='submissions_is_dele_f166e0_idx')],
            },
        ),
    ]
