# Generated by Django 5.2.9 on 2025-12-25 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, help_text='Format: COA-YYYY-NNN ili COB-YYYY-NNN', max_length=20, unique=True, verbose_name='Referentni Broj')),
                ('type', models.CharField(choices=[('COA', 'Prijava za Projekat'), ('COB', 'Prijava za Inicijativu')], max_length=3, verbose_name='Tip Prijave')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Podneto'), ('under_review', 'U Razmatranju'), ('approved', 'Odobreno'), ('rejected', 'Odbijeno')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Podneseno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Prijava',
                'verbose_name_plural': 'Prijave',
                'ordering': ['-submitted_at', '-created_at'],
                'indexes': [models.Index(fields=['reference_number'], name='submissions_referen_a37c83_idx'), models.Index(fields=['type', 'status'], name='submissions_type_3b79c4_idx'), models.Index(fields=['submitted_at'], name='submissions_submitt_0b8c3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('fizicko', 'Fizičko Lice'), ('pravno', 'Pravno Lice')], max_length=10, verbose_name='Tip Podnosioca')),
                ('ime', models.CharField(blank=True, max_length=100, verbose_name='Ime')),
                ('prezime', models.CharField(blank=True, max_length=100, verbose_name='Prezime')),
                ('jmbg', models.CharField(blank=True, help_text='13 cifara', max_length=13, verbose_name='JMBG')),
                ('naziv_organizacije', models.CharField(blank=True, max_length=200, verbose_name='Naziv Organizacije')),
                ('maticni_broj', models.CharField(blank=True, max_length=20, verbose_name='Matični Broj')),
                ('adresa', models.CharField(max_length=300, verbose_name='Adresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='submissions.application', verbose_name='Prijava')),
            ],
            options={
                'verbose_name': 'Podnosilac',
                'verbose_name_plural': 'Podnosioci',
            },
        ),
    ]
