# Generated by Django 5.2.9 on 2025-12-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_story_2_11_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencenumbersequence',
            name='application_type',
            field=models.CharField(choices=[('COA', 'Prijava za Projekat'), ('COB', 'Prijava za Inicijativu')], max_length=10, verbose_name='Tip Prijave'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['email'], name='applicant_email_idx'),
        ),
    ]
