# Generated by Django 5.2.9 on 2025-12-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aktivnosti',
            field=models.TextField(blank=True, help_text='Maksimalno 1500 karaktera', verbose_name='Aktivnosti'),
        ),
        migrations.AddField(
            model_name='application',
            name='budžet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Iznos u dinarima', max_digits=12, null=True, verbose_name='Totalni budžet (RSD)'),
        ),
        migrations.AddField(
            model_name='application',
            name='cilj',
            field=models.TextField(blank=True, help_text='Maksimalno 1000 karaktera', verbose_name='Glavni cilj'),
        ),
        migrations.AddField(
            model_name='application',
            name='ciljne_grupe',
            field=models.TextField(blank=True, help_text='Maksimalno 1500 karaktera', verbose_name='Ciljne grupe'),
        ),
        migrations.AddField(
            model_name='application',
            name='naslov',
            field=models.CharField(blank=True, help_text='Maksimalno 150 karaktera', max_length=150, verbose_name='Naslov projekta'),
        ),
        migrations.AddField(
            model_name='application',
            name='opis',
            field=models.TextField(blank=True, help_text='Maksimalno 500 karaktera', verbose_name='Kratak opis'),
        ),
        migrations.AddField(
            model_name='application',
            name='problem',
            field=models.TextField(blank=True, help_text='Maksimalno 2000 karaktera', verbose_name='Problem koji se rešava'),
        ),
        migrations.AddField(
            model_name='application',
            name='rezultati',
            field=models.TextField(blank=True, help_text='Maksimalno 1500 karaktera', verbose_name='Rezultati'),
        ),
        migrations.AddField(
            model_name='application',
            name='specifični_ciljevi',
            field=models.TextField(blank=True, help_text='Maksimalno 1000 karaktera', verbose_name='Specifični ciljevi'),
        ),
    ]
