# Generated by Django 5.2.9 on 2025-12-28 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_referencenumbersequence_application_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftMetadata',
            fields=[
                ('draft_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for draft (matches localStorage key UUID)', primary_key=True, serialize=False, verbose_name='Draft ID')),
                ('application_type', models.CharField(choices=[('COA', 'Projekat'), ('COB', 'Inicijativa')], help_text='Type of application (COA or COB)', max_length=3, verbose_name='Tip Prijave')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when draft was first created', verbose_name='Kreirano')),
                ('last_updated_at', models.DateTimeField(auto_now=True, help_text='Last time draft was updated (auto-save ping)', verbose_name='Poslednje Ažurirano')),
            ],
            options={
                'verbose_name': 'Draft Metadata',
                'verbose_name_plural': 'Draft Metadata Records',
                'db_table': 'submissions_draft_metadata',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='draft_created_idx'), models.Index(fields=['application_type'], name='draft_type_idx')],
            },
        ),
    ]
