# Generated by Django 5.2.9 on 2025-12-27 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_application_aktivnosti_application_budžet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='Original file name as uploaded by user', max_length=255, verbose_name='Originalni Naziv')),
                ('stored_filename', models.CharField(help_text='Unique filename used for storage', max_length=255, unique=True, verbose_name='Naziv u Skladištu')),
                ('file_path', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Putanja Fajla')),
                ('file_size', models.IntegerField(help_text='Size in bytes', verbose_name='Veličina Fajla')),
                ('file_type', models.CharField(help_text='File extension: pdf, doc, docx, xls, xlsx', max_length=10, verbose_name='Tip Fajla')),
                ('mime_type', models.CharField(help_text='Detected MIME type for validation', max_length=100, verbose_name='MIME Tip')),
                ('category', models.CharField(choices=[('BUDGET', 'Budžet'), ('BIOGRAPHY', 'Biografija'), ('SUPPORT_LETTER', 'Pismo Podrške')], help_text='Purpose of uploaded file', max_length=20, verbose_name='Kategorija')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Datum Upload-a')),
                ('uploaded_by_session', models.CharField(db_index=True, help_text='Session key for draft file ownership', max_length=40, verbose_name='Sesija Korisnika')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag', verbose_name='Obrisan')),
                ('application', models.ForeignKey(blank=True, help_text='Linked application (null for draft files)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='submissions.application', verbose_name='Prijava')),
            ],
            options={
                'verbose_name': 'Upload-ovani Fajl',
                'verbose_name_plural': 'Upload-ovani Fajlovi',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['uploaded_by_session'], name='submissions_uploade_b9ba48_idx'), models.Index(fields=['application'], name='submissions_applica_18d36e_idx'), models.Index(fields=['upload_date'], name='submissions_upload__105f27_idx'), models.Index(fields=['is_deleted'], name='submissions_is_dele_f166e0_idx')],
            },
        ),
    ]
