# Generated by Django 5.2.9 on 2025-12-28 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_draftmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='file_type',
            field=models.CharField(choices=[('BUDGET', 'Budžet'), ('BIOGRAPHY', 'Biografija'), ('SUPPORT_LETTER', 'Pismo Podrške'), ('OPIS_INICIJATIVE', 'Opis Inicijative'), ('PISMO_NAMERE', 'Pismo Namere')], max_length=20, verbose_name='Tip Fajla'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('BUDGET', 'Budžet'), ('BIOGRAPHY', 'Biografija'), ('SUPPORT_LETTER', 'Pismo Podrške'), ('OPIS_INICIJATIVE', 'Opis Inicijative'), ('PISMO_NAMERE', 'Pismo Namere')], help_text='Purpose of uploaded file', max_length=20, verbose_name='Kategorija'),
        ),
        migrations.CreateModel(
            name='InitiativeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=150, verbose_name='Naslov inicijative')),
                ('kratak_opis', models.TextField(max_length=500, verbose_name='Kratak opis')),
                ('problem', models.TextField(max_length=1500, verbose_name='Problem koji inicijativa rešava')),
                ('cilj_inicijative', models.TextField(max_length=1500, verbose_name='Cilj inicijative')),
                ('planirani_koraci', models.TextField(max_length=1500, verbose_name='Planirani koraci')),
                ('ocekivani_uticaj', models.TextField(max_length=1500, verbose_name='Očekivani uticaj na zajednicu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum kreiranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum izmene')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_data', to='submissions.application', verbose_name='Prijava')),
            ],
            options={
                'verbose_name': 'Podaci o inicijativi',
                'verbose_name_plural': 'Podaci o inicijativama',
                'db_table': 'submissions_initiative_data',
                'indexes': [models.Index(fields=['created_at'], name='submissions_created_4dd27f_idx'), models.Index(fields=['naslov'], name='submissions_naslov_f92662_idx')],
            },
        ),
    ]
