# Generated by Django 5.2.9 on 2025-12-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_filemetadata_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='entity_type',
            field=models.CharField(choices=[('fizicko', 'Fizičko Lice'), ('pravno', 'Pravno Lice')], db_index=True, max_length=10, verbose_name='Tip Podnosioca'),
        ),
    ]
