# Generated by Django 5.2.9 on 2025-12-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_add_entity_type_index_story_4_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('COA', 'Prijava za Projekat'), ('COB', 'Prijava za Inicijativu')], db_index=True, max_length=3, verbose_name='Tip prijave'),
        ),
        migrations.AlterField(
            model_name='referencenumbersequence',
            name='application_type',
            field=models.CharField(choices=[('COA', 'Prijava za Projekat'), ('COB', 'Prijava za Inicijativu')], max_length=10, verbose_name='Tip prijave'),
        ),
    ]
