# Generated by Django 5.2.9 on 2025-12-30 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_application_application_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When action was performed', verbose_name='Vreme')),
                ('action', models.CharField(db_index=True, help_text="Action type (e.g., 'viewed_application', 'changed_status')", max_length=50, verbose_name='Akcija')),
                ('old_value', models.TextField(blank=True, help_text='Previous value for changes (e.g., old status)', null=True, verbose_name='Stara Vrednost')),
                ('new_value', models.TextField(blank=True, help_text='New value for changes (e.g., new status)', null=True, verbose_name='Nova Vrednost')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of admin user (IPv4 or IPv6)', null=True, verbose_name='IP Adresa')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True, verbose_name='User Agent')),
                ('application', models.ForeignKey(blank=True, help_text='Application this action was performed on (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to='submissions.application', verbose_name='Prijava')),
                ('user', models.ForeignKey(help_text='Admin user who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Logs',
                'db_table': 'admin_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='admin_logs_timesta_f1fe82_idx'), models.Index(fields=['user'], name='admin_logs_user_id_c262c6_idx'), models.Index(fields=['action'], name='admin_logs_action_ff7830_idx'), models.Index(fields=['application'], name='admin_logs_applica_b80240_idx'), models.Index(fields=['action', '-timestamp'], name='admin_logs_action_time_idx')],
            },
        ),
    ]
