# Generated by Django 5.2.9 on 2026-01-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_admin_activity_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='jmbg',
            field=models.CharField(blank=True, help_text='Format: IDxxxxxx (npr. ID123456)', max_length=9, null=True, verbose_name='Broj lične karte / ID broj'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='maticni_broj',
            field=models.CharField(blank=True, help_text='Alfanumerički format (npr. REG-2024-ABC)', max_length=50, null=True, verbose_name='Registracioni broj'),
        ),
    ]
