# Generated by Django 5.2.9 on 2026-01-22 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_story_5_1_id_broj_registracioni_broj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanTima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime', models.CharField(blank=True, help_text='Puno ime člana tima', max_length=100, verbose_name='Ime i prezime')),
                ('email', models.EmailField(blank=True, help_text='Email adresa člana tima', max_length=254, verbose_name='Email')),
                ('telefon', models.CharField(blank=True, help_text='Broj telefona člana tima', max_length=30, verbose_name='Telefon')),
                ('application', models.ForeignKey(help_text='Application this team member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='clanovi_tima', to='submissions.application', verbose_name='Prijava')),
            ],
            options={
                'verbose_name': 'Član tima',
                'verbose_name_plural': 'Članovi tima',
                'db_table': 'submissions_clan_tima',
                'ordering': ['id'],
            },
        ),
    ]
