# Generated by Django 4.2 on 2026-01-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_story_5_1_clan_tima_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='datum_startovanja',
            field=models.DateField(blank=True, help_text='Planirani datum početka projekta', null=True, verbose_name='Datum startovanja'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='datum_zavrsetka',
            field=models.DateField(blank=True, help_text='Planirani datum završetka projekta', null=True, verbose_name='Datum završetka'),
        ),
    ]
