# Generated by Django 4.2 on 2026-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_story_5_2_project_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativedata',
            name='datum_startovanja',
            field=models.DateField(blank=True, help_text='Planirani datum početka inicijative', null=True, verbose_name='Datum startovanja'),
        ),
        migrations.AddField(
            model_name='initiativedata',
            name='datum_zavrsetka',
            field=models.DateField(blank=True, help_text='Planirani datum završetka inicijative', null=True, verbose_name='Datum završetka'),
        ),
        migrations.AddField(
            model_name='initiativedata',
            name='naziv_tima',
            field=models.CharField(blank=True, default='', help_text='Ime tima koji podnosi inicijativu', max_length=150, verbose_name='Naziv tima'),
        ),
        migrations.AddField(
            model_name='initiativedata',
            name='totalni_budzet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ukupan budžet u EUR', max_digits=12, null=True, verbose_name='Totalni budžet'),
        ),
        migrations.AlterField(
            model_name='initiativedata',
            name='planirani_koraci',
            field=models.TextField(max_length=1500, verbose_name='Planirane aktivnosti'),
        ),
    ]
