# Generated by Django 5.2 on 2026-07-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_story_5_4_file_type_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='consent_accuracy',
            field=models.BooleanField(default=False, verbose_name='Saglasnost - Tačnost podataka'),
        ),
        migrations.AddField(
            model_name='application',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vreme davanja saglasnosti'),
        ),
        migrations.AddField(
            model_name='application',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresa pri davanju saglasnosti'),
        ),
        migrations.AddField(
            model_name='application',
            name='consent_policy_version',
            field=models.CharField(blank=True, help_text='Verzija Politike privatnosti / Uslova korišćenja prihvaćena pri slanju', max_length=20, verbose_name='Verzija politike'),
        ),
        migrations.AddField(
            model_name='application',
            name='consent_privacy',
            field=models.BooleanField(default=False, verbose_name='Saglasnost - Politika privatnosti'),
        ),
        migrations.AddField(
            model_name='application',
            name='consent_terms',
            field=models.BooleanField(default=False, verbose_name='Saglasnost - Uslovi korišćenja'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('BUDGET', 'Budžet'), ('BIOGRAPHY', 'Biografija'), ('SUPPORT_LETTER', 'Pismo Podrške'), ('BUDZET_INICIJATIVE', 'Budžet Inicijative'), ('PISMO_PODRSKE', 'Pismo Podrške')], help_text='Purpose of uploaded file', max_length=20, verbose_name='Kategorija'),
        ),
    ]
