#!/usr/bin/env python3
"""
Z12 (2026-07-25): download the web fonts so the platform stops loading them from Google.

Until now base.css did `@import url('https://fonts.googleapis.com/...')`, which sends
every visitor's IP address to Google before they have agreed to anything - the exact
practice LG München I ruled against in January 2022 - while the privacy policy claimed
no third parties were involved. Google Fonts sets no cookie, so the cookie section of
the policy stayed true; the transfer itself was the problem.

Produces:
    static/fonts/*.woff2      the font files
    static/css/fonts.css      @font-face rules pointing at /static/fonts/

Rerun after changing FAMILIES (e.g. adding a weight), then collectstatic.
Requires network access; run it locally, commit the result, deploy the files.
"""
import re
import sys
import urllib.request
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
FONT_DIR = BASE / 'static' / 'fonts'
CSS_FILE = BASE / 'static' / 'css' / 'fonts.css'

# Exactly the families/weights base.css declares in --font-display/body/mono.
FAMILIES = [
    'Playfair+Display:wght@400;500;600;700',
    'Libre+Franklin:wght@300;400;500;600;700',
    'JetBrains+Mono:wght@400;500',
]

# Google serves one @font-face per unicode-range. Serbian latin needs latin-ext for
# č ć š ž đ; the cyrillic and vietnamese cuts are dead weight for this site.
WANTED_SUBSETS = {'latin', 'latin-ext'}

# Without a modern UA Google returns ttf/eot instead of woff2.
UA = ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) '
      'Chrome/120.0.0.0 Safari/537.36')


def fetch(url, binary=False):
    request = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(request, timeout=30) as response:
        data = response.read()
    return data if binary else data.decode('utf-8')


def main():
    FONT_DIR.mkdir(parents=True, exist_ok=True)

    url = 'https://fonts.googleapis.com/css2?' + '&'.join(
        f'family={family}' for family in FAMILIES
    ) + '&display=swap'
    print(f'Preuzimam CSS: {url}')
    css = fetch(url)

    # Each block is: /* subset */ @font-face { ... }
    blocks = re.findall(r'(/\*\s*([\w\-\[\]]+)\s*\*/\s*@font-face\s*\{.*?\})', css, re.S)
    if not blocks:
        sys.exit('GREŠKA: nijedan @font-face nije pronađen - Google je promenio format?')

    out = [
        '/*',
        ' * Self-hosted web fonts (Z12, 2026-07-25).',
        ' *',
        ' * Generated by scripts/fetch_fonts.py - do not edit by hand.',
        ' * Hosted locally on purpose: loading these from fonts.googleapis.com disclosed',
        ' * every visitor\'s IP address to a third party, which the privacy policy denies.',
        ' */',
        '',
    ]
    downloaded = 0

    for block, subset in blocks:
        if subset not in WANTED_SUBSETS:
            continue

        match = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", block)
        if not match:
            print(f'  preskačem {subset}: nema woff2 URL-a')
            continue
        remote = match.group(1)

        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r'font-weight:\s*(\d+)', block).group(1)
        style = re.search(r'font-style:\s*(\w+)', block).group(1)

        name = f"{family.lower().replace(' ', '-')}-{weight}-{style}-{subset}.woff2"
        (FONT_DIR / name).write_bytes(fetch(remote, binary=True))
        downloaded += 1
        print(f'  {name}')

        # Rewrite the src to the local copy; keep unicode-range so the browser still
        # only downloads the cut it needs for the text on the page.
        local_block = re.sub(r"src:\s*url\(https://[^)]+\)", f"src: url('../fonts/{name}')", block)
        local_block = re.sub(r'/\*.*?\*/\s*', '', local_block, flags=re.S)
        out.append(f'/* {family} {weight} {style} - {subset} */')
        out.append(local_block.strip())
        out.append('')

    CSS_FILE.write_text('\n'.join(out), encoding='utf-8')
    total = sum(f.stat().st_size for f in FONT_DIR.glob('*.woff2'))
    print(f'\nPreuzeto {downloaded} fajlova ({total / 1024:.0f} KB) -> {FONT_DIR}')
    print(f'Napisan {CSS_FILE}')


if __name__ == '__main__':
    main()
